# Copyright 2025 The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Public API and wrapper generation for SpeculativeDecodingTrainer instrumentation."""

import inspect
import textwrap

from kubeflow.trainer.rhai.instrumentation.speculator_progression import (
    _create_speculator_progression_instrumentation,
)


def get_speculator_instrumentation_wrapper(
    metrics_port: int,
    mode: str,
    num_epochs: int = 0,
) -> str:
    """Generate self-contained instrumentation wrapper via inspect.getsource.

    Args:
        metrics_port: Port for HTTP metrics server.
        mode: Speculator mode string ("data_only", "train_only").
        num_epochs: Total training epochs.

    Returns:
        Python code as string with {{user_training_code}} placeholder.
    """
    instrumentation_code = inspect.getsource(_create_speculator_progression_instrumentation)
    instrumentation_code = textwrap.dedent(instrumentation_code)

    wrapper = f"""\
# =============================================================================
# Kubeflow SDK - Speculator Progression Tracking Instrumentation
# Generated by kubeflow.trainer.rhai.instrumentation.speculator
# =============================================================================

import os as _instr_os
_local_rank = int(_instr_os.environ.get("LOCAL_RANK", "0"))

print("[Kubeflow] Initializing speculator progression tracking", flush=True)

# Instrumentation function definition
{instrumentation_code}

if _local_rank == 0:
    # Initialize and apply instrumentation
    (
        _apply_progression_tracking,
        _start_data_progress_server,
        _,
        _mark_data_complete,
        _set_phase,
    ) = _create_speculator_progression_instrumentation(
        metrics_port={metrics_port},
        mode={mode!r},
        num_epochs={num_epochs},
    )
    _set_steps_per_epoch = _apply_progression_tracking()
    print("[Kubeflow] Speculator progression tracking enabled", flush=True)

# =============================================================================
# USER CODE
# =============================================================================

{{{{user_training_code}}}}"""

    return wrapper
