"""Public API and wrapper generation for TrainingHubTrainer instrumentation."""

import inspect
import textwrap

from kubeflow.trainer.rhai.instrumentation.traininghub_progression import (
    _create_training_hub_progression_instrumentation,
)


def get_training_hub_instrumentation_wrapper(
    algorithm: str,
    ckpt_output_dir: str,
    metrics_port: int = 28080,
) -> str:
    """Generate self-contained instrumentation wrapper via inspect.getsource.

    Extracts _create_training_hub_progression_instrumentation as source code and injects
    a call with the provided parameters.

    Args:
        algorithm: Training Hub algorithm name ("sft" or "osft")
        ckpt_output_dir: Directory where metrics files are written
        metrics_port: Port for HTTP metrics server

    Returns:
        Python code as string to be injected before training code

    Raises:
        ValueError: If algorithm is not supported (via get_algorithm_pod_metadata).
    """
    from kubeflow.trainer.algorithms import get_algorithm_pod_metadata

    if not isinstance(metrics_port, int) or not (1024 <= metrics_port <= 65535):
        raise ValueError(f"metrics_port must be an int in [1024, 65535], got {metrics_port!r}")

    # Resolve algorithm metadata from centralized registry
    # This validates the algorithm name and retrieves its metadata
    algorithm_metadata = get_algorithm_pod_metadata(algorithm)

    # Extract the entire function source
    instrumentation_code = inspect.getsource(_create_training_hub_progression_instrumentation)
    instrumentation_code = textwrap.dedent(instrumentation_code)

    # Build the wrapper with function call
    wrapper = f"""# =============================================================================
# Kubeflow SDK - Training Hub Progression Tracking Instrumentation
# Generated by kubeflow.trainer.rhai.traininghub_instrumentation
# =============================================================================

print("[Kubeflow] Initializing Training Hub progression tracking", flush=True)

# Instrumentation function definition
{instrumentation_code}

# Initialize and apply instrumentation
(
    apply_progression_tracking,
    _,
) = _create_training_hub_progression_instrumentation(
    algorithm_metadata={algorithm_metadata!r},
    ckpt_output_dir={ckpt_output_dir!r},
    metrics_port={metrics_port!r}
)
apply_progression_tracking()
print("[Kubeflow] Training Hub progression tracking enabled", flush=True)

# =============================================================================
# USER TRAINING CODE STARTS BELOW
# =============================================================================

"""

    return wrapper


# Re-exports for backward compatibility
from kubeflow.trainer.rhai.instrumentation.traininghub_codegen import (  # noqa: E402, F401
    _get_command_from_runtime,
    _render_algorithm_wrapper,
    _render_dict_literal,
    _render_user_func_code,
)
