# Copyright 2024 The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Public API and wrapper generation for TrainingHubTrainer instrumentation."""

import inspect
import textwrap

from kubeflow.trainer.rhai.instrumentation.traininghub_progression import (
    _create_training_hub_progression_instrumentation,
)


def get_training_hub_instrumentation_wrapper(
    algorithm: str,
    ckpt_output_dir: str,
    metrics_port: int = 28080,
) -> str:
    """Generate self-contained instrumentation wrapper via inspect.getsource.

    Extracts _create_training_hub_progression_instrumentation as source code and injects
    a call with the provided parameters.

    Args:
        algorithm: Training Hub algorithm name ("sft" or "osft")
        ckpt_output_dir: Directory where metrics files are written
        metrics_port: Port for HTTP metrics server

    Returns:
        Python code as string to be injected before training code

    Raises:
        ValueError: If algorithm is not supported (via get_algorithm_pod_metadata).
    """

    from kubeflow.trainer.algorithms import get_algorithm_pod_metadata

    # Resolve algorithm metadata from centralized registry
    # This validates the algorithm name and retrieves its metadata
    algorithm_metadata = get_algorithm_pod_metadata(algorithm)

    # Extract the entire function source
    instrumentation_code = inspect.getsource(_create_training_hub_progression_instrumentation)
    instrumentation_code = textwrap.dedent(instrumentation_code)

    # Build the wrapper with function call
    wrapper = f"""# =============================================================================
# Kubeflow SDK - Training Hub Progression Tracking Instrumentation
# Generated by kubeflow.trainer.rhai.traininghub
# =============================================================================

print("[Kubeflow] Initializing Training Hub progression tracking", flush=True)

# Instrumentation function definition
{instrumentation_code}

# Initialize and apply instrumentation
(
    apply_progression_tracking,
    _,
) = _create_training_hub_progression_instrumentation(
    algorithm_metadata={algorithm_metadata!r},
    ckpt_output_dir={ckpt_output_dir!r},
    metrics_port={metrics_port}
)
apply_progression_tracking()
print("[Kubeflow] Training Hub progression tracking enabled", flush=True)

# =============================================================================
# USER TRAINING CODE STARTS BELOW
# =============================================================================

"""

    return wrapper
