# Copyright 2024 The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Serialize Training Hub callbacks for injection into training pod scripts."""

from __future__ import annotations

import inspect
import textwrap
from typing import Any

_HUB_CALLBACKS_VAR = "_KUBEFLOW_HUB_CALLBACKS"
_TRAINING_HUB_API_NAMES = ("sft", "osft", "lora_sft", "lora_grpo")


def _callback_class(callback: Any) -> type:
    """Return the callback class from a class or instance."""
    if isinstance(callback, type):
        return callback
    return type(callback)


def validate_callbacks(callbacks: list[Any] | None) -> None:
    """Validate callbacks before CRD generation.

    Args:
        callbacks: User-provided callback classes or instances.

    Raises:
        TypeError: If callbacks is not a list or contains invalid entries.
        ValueError: If a callback class cannot be serialized with inspect.getsource.
    """
    if callbacks is None:
        return

    if not isinstance(callbacks, list):
        raise TypeError(f"callbacks must be a list, got {type(callbacks).__name__}")

    for callback in callbacks:
        if isinstance(callback, str):
            raise TypeError(
                f"Each callback must be a class or instance, got {type(callback).__name__}"
            )
        cls = _callback_class(callback)
        if not isinstance(cls, type):
            raise TypeError(
                f"Each callback must be a class or instance, got {type(callback).__name__}"
            )
        try:
            inspect.getsource(cls)
        except (OSError, TypeError) as exc:
            name = getattr(cls, "__name__", repr(callback))
            raise ValueError(
                f"Callback {name!r} must be defined in a regular Python source file "
                "so it can be serialized into the training pod. "
                "Define the callback at module level, not inside a function or REPL."
            ) from exc


def build_training_hub_callback_injection_code(callbacks: list[Any]) -> str:
    """Generate pod script preamble that defines and registers Training Hub callbacks.

    Serializes each callback class with inspect.getsource, instantiates them in the pod,
    and patches training_hub entrypoints so callbacks reach sft/osft/lora_sft/lora_grpo.

    Args:
        callbacks: Callback classes or instances supplied on TrainingHubTrainer.

    Returns:
        Python source to prepend before generated training code.
    """
    if not callbacks:
        return ""

    callback_sources: list[str] = []
    class_names: list[str] = []
    for callback in callbacks:
        cls = _callback_class(callback)
        source = textwrap.dedent(inspect.getsource(cls))
        callback_sources.append(source)
        class_names.append(cls.__name__)

    all_callback_code = "\n\n".join(callback_sources)
    instantiation_lines = ", ".join(f"{name}()" for name in class_names)

    return f"""# =============================================================================
# Kubeflow SDK - Training Hub Callback Injection
# Generated by kubeflow.trainer.rhai.traininghub
# =============================================================================

from training_hub import TrainingHubCallback, TrainingHubContext
import training_hub as _kubeflow_training_hub

# --- User callback definitions ---
{all_callback_code}

{_HUB_CALLBACKS_VAR} = [{instantiation_lines}]
print(f"[Kubeflow] Prepared {{len({_HUB_CALLBACKS_VAR})}} Training Hub callback(s)", flush=True)


def _kubeflow_wrap_training_hub_api(_orig_fn, _extra_callbacks):
    def _wrapped(*args, **kwargs):
        merged = list(kwargs.get("callbacks") or [])
        merged.extend(_extra_callbacks)
        kwargs["callbacks"] = merged
        return _orig_fn(*args, **kwargs)

    return _wrapped


for _api_name in {_TRAINING_HUB_API_NAMES!r}:
    _orig_api = getattr(_kubeflow_training_hub, _api_name, None)
    if _orig_api is not None:
        setattr(
            _kubeflow_training_hub,
            _api_name,
            _kubeflow_wrap_training_hub_api(_orig_api, {_HUB_CALLBACKS_VAR}),
        )

print("[Kubeflow] Training Hub callback injection configured", flush=True)
"""
