# Copyright 2024 The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Public API and code-injection utilities for TransformersTrainer instrumentation."""

import inspect
import textwrap

from kubeflow.trainer.rhai.instrumentation.transformers_checkpoint import (
    _create_checkpoint_instrumentation,
)
from kubeflow.trainer.rhai.instrumentation.transformers_progression import (
    _create_progression_instrumentation,
)


def get_transformers_instrumentation_wrapper(
    metrics_port: int,
) -> str:
    """Generate self-contained instrumentation wrapper via inspect.getsource.

    Extracts _create_progression_instrumentation as source code and injects a call
    with the provided metrics_port parameter.

    Args:
        metrics_port: Port for HTTP metrics server.

    Returns:
        Python code as string with {{user_func_import_and_call}} placeholder.
    """
    # Extract the entire function source
    progression_instrumentation_code = inspect.getsource(_create_progression_instrumentation)
    progression_instrumentation_code = textwrap.dedent(progression_instrumentation_code)

    # Build the wrapper with function call
    wrapper = f"""# =============================================================================
# Kubeflow SDK - Progression Tracking Instrumentation
# Generated by kubeflow.trainer.rhai.transformers_instrumentation
# =============================================================================

print("[Kubeflow] Initializing progression tracking", flush=True)

# Instrumentation function definition
{progression_instrumentation_code}

# Initialize and apply instrumentation
(
    apply_progression_tracking,
    _,
    _,
    _,
    _,
) = _create_progression_instrumentation(metrics_port={metrics_port})
apply_progression_tracking()
print("[Kubeflow] Progression tracking enabled", flush=True)

# =============================================================================
# USER TRAINING CODE
# =============================================================================

{{{{user_func_import_and_call}}}}"""

    return wrapper


def get_jit_checkpoint_injection_code(
    output_dir: str | None = None,
    cloud_remote_storage_uri: str | None = None,
    periodic_checkpoint_config: dict | None = None,
    enable_jit_checkpoint: bool = False,
    verify_cloud_storage_access: bool = True,
    verify_cloud_storage_ssl: bool = True,
) -> tuple[str, str]:
    """Generate the complete JIT checkpoint code to inject into training scripts.

    Returns:
        Tuple of (header_code, footer_code). Header initializes checkpoint instrumentation
        and runs before user code. Footer uploads final model artifacts and runs after.
    """
    from kubeflow.trainer.rhai.constants import CHECKPOINT_INCOMPLETE_MARKER, CHECKPOINT_STAGING_DIR

    # Build checkpoint config dict
    config_dict = {
        "enable_jit": enable_jit_checkpoint,
        "verify_cloud_storage_access": verify_cloud_storage_access,
        "verify_cloud_storage_ssl": verify_cloud_storage_ssl,
    }

    if output_dir:
        config_dict["output_dir"] = output_dir

    if cloud_remote_storage_uri:
        config_dict["cloud_remote_storage_uri"] = cloud_remote_storage_uri

    if periodic_checkpoint_config:
        if "save_strategy" in periodic_checkpoint_config:
            config_dict["save_strategy"] = periodic_checkpoint_config["save_strategy"]
        if "save_steps" in periodic_checkpoint_config:
            config_dict["save_steps"] = periodic_checkpoint_config["save_steps"]
        if "save_total_limit" in periodic_checkpoint_config:
            config_dict["save_total_limit"] = periodic_checkpoint_config["save_total_limit"]

    # Extract the entire function source
    checkpoint_instrumentation_code = inspect.getsource(_create_checkpoint_instrumentation)
    checkpoint_instrumentation_code = textwrap.dedent(checkpoint_instrumentation_code)

    # Remove the import that won't be available in training pods (we'll define it globally instead)
    constants_import = (
        "from kubeflow.trainer.rhai.constants import CHECKPOINT_INCOMPLETE_MARKER, "
        "CHECKPOINT_STAGING_DIR"
    )
    if constants_import not in checkpoint_instrumentation_code:
        raise RuntimeError(
            "Expected constants import missing from checkpoint instrumentation source; "
            "cannot strip SDK dependency for training pods"
        )
    checkpoint_instrumentation_code = checkpoint_instrumentation_code.replace(
        constants_import,
        "# Constants defined globally above",
    )

    # Serialize config dict as Python code
    import pprint

    config_dict_str = pprint.pformat(config_dict, indent=4, width=100, sort_dicts=False)

    # Build the header (runs before user code)
    header = f"""# =============================================================================
# Kubeflow SDK - Checkpoint Instrumentation
# Generated by kubeflow.trainer.rhai.transformers_instrumentation
# =============================================================================

print("[Kubeflow] Initializing checkpoint instrumentation", flush=True)

# Constants (inline to avoid import dependencies in training pods)
CHECKPOINT_INCOMPLETE_MARKER = {repr(CHECKPOINT_INCOMPLETE_MARKER)}
CHECKPOINT_STAGING_DIR = {repr(CHECKPOINT_STAGING_DIR)}

# Instrumentation function definition
{checkpoint_instrumentation_code}

# Initialize and apply instrumentation
checkpoint_config = {config_dict_str}
_, _, apply_checkpointing, upload_final_model_to_cloud = _create_checkpoint_instrumentation(checkpoint_config)
apply_checkpointing()
print("[Kubeflow] Checkpoint instrumentation enabled", flush=True)
"""

    # Build the footer (runs after user code)
    footer = """
# =============================================================================
# Kubeflow SDK - Post-Training Cleanup
# =============================================================================
upload_final_model_to_cloud()
"""

    return header, footer
