# Copyright 2024 The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""TransformersTrainer for HuggingFace Transformers and TRL with auto-instrumentation."""

from dataclasses import dataclass, field
from typing import Callable, Optional

from kubeflow.trainer.constants import constants


@dataclass
class TransformersTrainer:
    """RHAI trainer for HuggingFace Transformers and TRL with auto-instrumentation.

    Provides instrumentation for:
    - Training progression tracking via HTTP metrics endpoint
    - Custom metrics tracking via callback

    Supported Trainers (via base class patching):
    - transformers.Trainer (standard fine-tuning)
    - trl.SFTTrainer (Supervised Fine-Tuning)
    - trl.DPOTrainer (Direct Preference Optimization)
    - trl.PPOTrainer (Proximal Policy Optimization)
    - trl.RewardTrainer (Reward Model Training)
    - Any other Trainer subclass

    When to use:
    - You need real-time progress tracking in the UI
    - You're using HuggingFace Transformers or TRL
    - You want to track custom metrics beyond loss/lr

    Args:
        func: The function that encapsulates the entire model training process.
        func_args: The arguments to pass to the function.
        packages_to_install: A list of Python packages to install before running the function.
        pip_index_urls: The PyPI URLs from which to install Python packages.
                       The first URL will be the index-url, and remaining ones are extra-index-urls.
        num_nodes: The number of nodes to use for training.
        resources_per_node: The computing resources to allocate per node.
        env: The environment variables to set in the training nodes.
        enable_progression_tracking: Enable HTTP metrics server. Default: True.
        metrics_port: Port for HTTP metrics server. Default: 28080.
        metrics_poll_interval_seconds: How often controller should poll metrics (seconds).
                                       Default: 30. Lower values = more frequent updates,
                                       higher controller load. Recommended range: 5-60 seconds.
        custom_metrics: Dict mapping log keys to metric names to track.
                       Example: {"eval_accuracy": "accuracy", "custom_metric": "custom"}
                       These will be exposed in the /metrics endpoint.
    """

    # Core training function (same as CustomTrainer)
    func: Callable
    func_args: Optional[dict] = None
    packages_to_install: Optional[list[str]] = None
    pip_index_urls: list[str] = field(
        default_factory=lambda: list(constants.DEFAULT_PIP_INDEX_URLS)
    )
    num_nodes: Optional[int] = None
    resources_per_node: Optional[dict] = None
    env: Optional[dict[str, str]] = None

    # Instrumentation features
    enable_progression_tracking: bool = True
    metrics_port: int = 28080
    metrics_poll_interval_seconds: int = 30
    custom_metrics: Optional[dict[str, str]] = field(default_factory=dict)


def get_transformers_instrumentation_wrapper(
    metrics_port: int,
    custom_metrics: dict[str, str],
) -> str:
    """Generate self-contained instrumentation wrapper script.

    This creates a complete Python script that includes the HTTP server,
    progress callback, and Trainer monkey-patching - all without requiring
    any SDK imports at runtime.

    Args:
        metrics_port: Port for HTTP metrics server.
        custom_metrics: Dict mapping log keys to metric names.

    Returns:
        Python code as string with {{user_func_import_and_call}} placeholder.
    """
    import json

    custom_metrics_json = json.dumps(custom_metrics)

    return f'''
# =============================================================================
# KUBEFLOW SDK - SELF-CONTAINED INSTRUMENTATION WRAPPER
# Generated by kubeflow.trainer.rhai.transformers
# No SDK imports needed - all code is self-contained
# =============================================================================

import http.server
import json
import socketserver
import threading
import time
from datetime import datetime
from typing import Optional

# =============================================================================
# HTTP METRICS SERVER
# =============================================================================

class ProgressMetricsHandler(http.server.BaseHTTPRequestHandler):
    """HTTP handler that serves training progress metrics as JSON."""

    metrics = {{
        "status": "initializing",
        "status_message": "Training initialization in progress",
        "status_details": {{"last_event": "init", "last_event_time": None, "warnings": []}},
        "progress": {{"step_current": 0, "step_total": 0, "percent": 0.0, "epoch": 0}},
        "time": {{
            "started_sec": None,
            "started_at": None,
            "elapsed_sec": 0,
            "elapsed": "0s",
            "remaining_sec": None,
            "remaining": None,
            "updated_sec": None,
            "updated_at": None,
        }},
        "metrics": {{
            "loss": None,
            "learning_rate": None,
            "throughput_samples_sec": None,
        }},
    }}
    metrics_lock = threading.Lock()

    def log_message(self, format, *args):
        """Suppress default HTTP server logging."""
        pass

    def do_GET(self):
        """Respond to GET requests with health check or metrics."""
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"OK")
        elif self.path in ("/", "/metrics"):
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            metrics_json = ProgressMetricsHandler.get_metrics_json()
            self.wfile.write(metrics_json.encode("utf-8"))
        else:
            self.send_response(404)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"Not Found")

    @classmethod
    def update_metrics(cls, updates: dict):
        """Thread-safe update of metrics dict."""
        with cls.metrics_lock:
            def deep_update(target, source):
                for key, value in source.items():
                    if isinstance(value, dict) and key in target and isinstance(target[key], dict):
                        deep_update(target[key], value)
                    else:
                        target[key] = value
            deep_update(cls.metrics, updates)

    @classmethod
    def get_metrics_json(cls) -> str:
        """Thread-safe read of metrics as JSON string."""
        with cls.metrics_lock:
            return json.dumps(cls.metrics, indent=2)


def start_metrics_server(port: int = {metrics_port}):
    """Start HTTP server in background thread."""
    socketserver.TCPServer.allow_reuse_address = True
    server = socketserver.TCPServer(("", port), ProgressMetricsHandler)

    server_thread = threading.Thread(
        target=server.serve_forever, daemon=True, name="metrics-server"
    )
    server_thread.start()

    print(f"[Kubeflow] Metrics server started on port {{port}}", flush=True)
    return server


# =============================================================================
# PROGRESS TRACKING CALLBACK
# =============================================================================

from transformers import TrainerCallback


class KubeflowProgressCallback(TrainerCallback):
    """Callback that tracks training progress and exposes via HTTP metrics."""

    def __init__(self) -> None:
        """Initialize progress callback."""
        self.start_time: Optional[float] = None
        self.custom_metrics_map = {custom_metrics_json}

    @staticmethod
    def _format_duration(seconds: Optional[float]) -> Optional[str]:
        """Format seconds into human-readable duration."""
        if seconds is None or seconds < 0:
            return None

        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)

        if hours > 0:
            return f"{{hours}}h {{minutes}}m {{secs}}s"
        elif minutes > 0:
            return f"{{minutes}}m {{secs}}s"
        else:
            return f"{{secs}}s"

    @staticmethod
    def _format_timestamp(timestamp: Optional[float]) -> Optional[str]:
        """Format Unix timestamp to ISO 8601 string."""
        if timestamp is None:
            return None
        return datetime.fromtimestamp(timestamp).strftime("%Y-%m-%d %H:%M:%S")

    def on_train_begin(self, args, state, control, **kwargs) -> None:
        """Called when training begins."""
        self.start_time = time.time()

        ProgressMetricsHandler.update_metrics({{
            "status": "training",
            "status_message": "Training started",
            "status_details": {{
                "last_event": "training_started",
                "last_event_time": self._format_timestamp(self.start_time),
            }},
            "progress": {{
                "step_current": state.global_step,
                "step_total": state.max_steps,
                "percent": 0.0,
                "epoch": state.epoch if hasattr(state, "epoch") else 0,
            }},
            "time": {{
                "started_sec": self.start_time,
                "started_at": self._format_timestamp(self.start_time),
                "updated_sec": self.start_time,
                "updated_at": self._format_timestamp(self.start_time),
            }},
        }})

    def on_step_end(self, args, state, control, **kwargs) -> None:
        """Called at the end of each training step."""
        current_time = time.time()
        current_step = state.global_step
        total_steps = state.max_steps

        progress_pct = (current_step / total_steps * 100) if total_steps > 0 else 0

        elapsed_sec = current_time - self.start_time if self.start_time else 0
        remaining_sec = None
        if current_step > 0 and elapsed_sec > 0:
            estimated_total_time = elapsed_sec / (current_step / total_steps)
            remaining_sec = estimated_total_time - elapsed_sec

        remaining_str = (
            self._format_duration(remaining_sec) if remaining_sec else "calculating..."
        )
        status_msg = (
            f"Training in progress: {{progress_pct:.1f}}% complete, "
            f"{{remaining_str}} remaining"
        )

        ProgressMetricsHandler.update_metrics({{
            "status_message": status_msg,
            "progress": {{
                "step_current": current_step,
                "step_total": total_steps,
                "percent": round(progress_pct, 2),
                "epoch": state.epoch,
            }},
            "time": {{
                "elapsed_sec": round(elapsed_sec, 2),
                "elapsed": self._format_duration(elapsed_sec),
                "remaining_sec": round(remaining_sec, 2) if remaining_sec else None,
                "remaining": self._format_duration(remaining_sec) if remaining_sec else None,
                "updated_sec": current_time,
                "updated_at": self._format_timestamp(current_time),
            }},
        }})

    def on_log(self, args, state, control, logs=None, **kwargs):
        """Called when Trainer logs metrics."""
        if logs:
            metrics_update = {{}}

            # Track standard metrics
            if "loss" in logs:
                metrics_update["loss"] = logs["loss"]
            if "learning_rate" in logs:
                metrics_update["learning_rate"] = logs["learning_rate"]
            if "train_samples_per_second" in logs:
                metrics_update["throughput_samples_sec"] = logs["train_samples_per_second"]

            # Track custom metrics
            if self.custom_metrics_map:
                for log_key, metric_name in self.custom_metrics_map.items():
                    if log_key in logs:
                        metrics_update[metric_name] = logs[log_key]

            if metrics_update:
                current_time = time.time()
                ProgressMetricsHandler.update_metrics({{
                    "metrics": metrics_update,
                    "time": {{
                        "updated_sec": current_time,
                        "updated_at": self._format_timestamp(current_time),
                    }},
                }})

    def on_train_end(self, args, state, control, **kwargs) -> None:
        """Called when training ends."""
        end_time = time.time()
        total_time = end_time - self.start_time if self.start_time else 0

        current_metrics = json.loads(ProgressMetricsHandler.get_metrics_json())
        final_step = current_metrics.get("progress", {{}}).get("step_current", 0)
        status_msg = (
            f"Training completed successfully at step {{final_step}} in "
            f"{{self._format_duration(total_time)}}"
        )

        ProgressMetricsHandler.update_metrics({{
            "status": "completed",
            "status_message": status_msg,
            "status_details": {{
                "last_event": "training_completed",
                "last_event_time": self._format_timestamp(end_time),
            }},
            "progress": {{
                "percent": 100.0,
            }},
            "time": {{
                "elapsed_sec": round(total_time, 2),
                "elapsed": self._format_duration(total_time),
                "remaining_sec": 0,
                "remaining": "0s",
                "updated_sec": end_time,
                "updated_at": self._format_timestamp(end_time),
            }},
        }})


# =============================================================================
# INSTRUMENT TRANSFORMERS.TRAINER
# =============================================================================

from transformers import trainer as trainer_module

_original_trainer_init = trainer_module.Trainer.__init__


def _instrumented_trainer_init(self, *args, **kwargs):
    """Instrumented __init__ that injects KubeflowProgressCallback."""
    existing_callbacks = kwargs.get("callbacks")
    if existing_callbacks is None:
        callbacks = []
    elif isinstance(existing_callbacks, TrainerCallback):
        callbacks = [existing_callbacks]
    else:
        callbacks = list(existing_callbacks) if existing_callbacks else []

    # Inject our callback
    callbacks.append(KubeflowProgressCallback())
    kwargs["callbacks"] = callbacks

    # Call original __init__
    _original_trainer_init(self, *args, **kwargs)


trainer_module.Trainer.__init__ = _instrumented_trainer_init
print("[Kubeflow] Transformers.Trainer instrumentation active (patched base class)", flush=True)

# Start metrics server
_metrics_server = start_metrics_server(port={metrics_port})

# =============================================================================
# USER TRAINING CODE
# =============================================================================

{{{{user_func_import_and_call}}}}
'''
